### ISSUE TITLE
Reference Data

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/gss-data-docs#14]
- [ ] GSS-Cogs/gss-utils#65.
- [ ] Multiple measures in mapping. GSS-Cogs/gss-utils#93
- [x] Manage / upload dataset specific definitions.
- [ ] Manage / upload family level definitions. GSS-Cogs/pmd-jenkins-library#17
- [x] Manage / upload common definitions. GSS-Cogs/ref_common#3
- [x] Manage / upload external definitions.
- [ ] Manage / upload geographies.
- [x] Manage / upload time intervals.
- [ ] Reference data catalogues
